<?php
/**
 * Magenable
 *
 * @category    Magenable
 * @package     Magenable_TopBarNotification
 * @copyright   Copyright (c) Magenable (https://magenable.com.au/)
 */
declare(strict_types=1);

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $view \Magenable\TopBarNotification\ViewModel\Notification */
$view = $block->getData('details');
$escaper = $view->getEscaper(); // get escaper from view model for backward compatibility
?>
<?php if ($view->isTextNotification()): ?>
<div class="top-bar-notification hidden tbn-type-text"
    data-mage-init='<?= $escaper->escapeHtmlAttr($view->getConfigData()) ?>'
    style="background-color: <?= /* @noEscape */ $view->getBackgroundColor() ?>">
    <div class="tbn-text" style="
             color: <?= /* @noEscape */ $view->getTextColor() ?>;
             font-size: <?= /* @noEscape */ $view->getFontSize() ?>">
        <?= $escaper->escapeHtml($view->getText()) ?>
    </div>
    <div id="tbn-close-btn" class="tbn-close-btn"></div>
</div>
<?php else: ?>
<div class="top-bar-notification hidden tbn-type-html"
    data-mage-init='<?= $escaper->escapeHtmlAttr($view->getConfigData()) ?>'>
    <?= $view->getHtmlContent() ?>
    <div id="tbn-close-btn" class="tbn-close-btn"></div>
</div>
<?php endif; ?>
